resolver: lts-14.12

packages:
- schema
- rpc
- grpc
- examples/health-check
- examples/route-guide

extra-deps:
- proto3-wire-1.0.0
- http2-client-0.9.0.0
- primitive-0.7.0.0
- primitive-extras-0.8
- primitive-unlifted-0.1.2.0
- stm-hamt-1.2.0.4
- stm-containers-1.1.0.4
- AC-Angle-1.0
- git: https://github.com/serras/avro.git
  commit: 7ba39ebb6b74c64fffb3d3a972b4000185579f19
- git: https://github.com/higherkindness/http2-grpc-haskell.git
  commit: 2be0f0675d52db8e7142aa80176a35eed8b4ca14
  subdirs:
    - http2-grpc-types
    - http2-grpc-proto3-wire
    - warp-grpc
    - http2-client-grpc
- git: https://github.com/higherkindness/protobuf-parser-haskell
  commit: 547fe3c9e0f076b381d94837c676c9b5a2b6753e
