resolver: lts-14.7

packages:
- .

extra-deps:
- proto3-wire-1.0.0
- http2-grpc-types-0.4.0.0
- git: https://github.com/serras/avro.git
  commit: 7ba39ebb6b74c64fffb3d3a972b4000185579f19
- git: https://github.com/47deg/warp-grpc.git
  commit: d8cd78f0a8d78119df27e3271bc5204d7b26aeb8
- git: https://github.com/higherkindness/mu-haskell.git
  commit: ddb8e22863915954521c223af724dd7d6a247e8a
  subdirs:
    - schema
    - rpc
    - grpc